#!/bin/bash
set -e

source "$(dirname "$(realpath "$0")")"/functions.sh

# check brew exists, otherwise this script is useless
command_exists brew || (echo "Homebrew is not installed!" && return 1)

install_brew_packages
install_ohmyzsh
install_neovim_extensions

# TODO: This breaks docker builds :)
# install_fonts

DECRYPT=${DECRYPT:-no}
if [ $DECRYPT = yes ]; then
  yadm decrypt
else
  echo "Skipping encrypted files, as requested"
fi
