#!/bin/bash
set -e

source "$(dirname "$(realpath "$0")")"/functions.sh

command_exists() {
  command -v "$@" >/dev/null 2>&1
}

# check brew exists, otherwise this script is useless
command_exists brew || (echo "Homebrew is not installed!" && return 1)

install_brew_packages
install_pip_packages
install_ohmyzsh
install_neovim_extensions

DECRYPT=${DECRYPT:-no}
if [ $DECRYPT = yes ]; then
  yadm decrypt
else
  echo "Skipping encrypted files, as requested"
fi
