#!/bin/bash
# @file      mount_datasets
# @author    Ignacio Vizzo     [ivizzo@uni-bonn.de]
#
# Copyright (c) 2019 Ignacio Vizzo, all rights reserved

# First umount all the mounted remote file systems, just in case
LOCATION=$HOME/webserver
mkdir -p $LOCATION
fusermount -q -u $LOCATION

# Mount this directory as read only so we don't screw up anything
echo "Mounting webserver into $HOME/dataserver/"
sshfs -o reconnect,rw,ServerAliveInterval=15,ServerAliveCountMax=3,IdentityFile=$HOME/.ssh/id_rsa \
  nacho@webserver:/export/wwwroot/ipb/ \
  $LOCATION
