name: On-Push

on:
  push:
    branches:
      - main

jobs:
  on_push:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run YADM Bootstrap
        run: |
          brew install yadm
