name: cpp_project
on_project_start: cmake -Bbuild && cmake --build build
windows:
  - build:
      layout: even-horizontal
      panes:
        - vim main.cpp
        - find . | entr -c './build_and_run.sh'
